services:
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile

  upstream-data:
    build:
      context: .
      dockerfile: services/upstream-data/Dockerfile

  image-renderer:
    build:
      context: .
      dockerfile: services/image-renderer/Dockerfile

  postgres:
    ports:
      - "127.0.0.1:5432:5432"
